# Generated by Django 5.1.3 on 2024-11-27 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_paciente_redes_sociais'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='indicado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenciados', to='api.paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='parentes',
            field=models.ForeignKey(blank=True, choices=[('pai', 'Pai'), ('mae', 'Mãe'), ('irma', 'Irmã'), ('filho', 'Filho'), ('avo', 'Avô/Avó')], null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parente', to='api.paciente'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateField(blank=True),
        ),
    ]
